/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Aulas extends javax.swing.JFrame{
    
    int xMouse, yMouse;

    public void mostrar() {
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sql = "Select * from aula";
            Statement st = null;
            DefaultTableModel model = new DefaultTableModel();
            //añadir el nombre de la columna
            model.addColumn("ID");
            model.addColumn("Capacidad");
            model.addColumn("Edificio");
            tablaAulas.setModel(model);

            String[] datos = new String[3];
            try {
                st = (Statement) conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    model.addRow(datos);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            // Cerrar la conexión
            st.close();
            conn.close();
        } catch (SQLException e) {

        }
    } 
    public Aulas() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ButtonIngresarAulas = new javax.swing.JButton();
        ButtonEliminarAulas = new javax.swing.JButton();
        ButtonModificarAulas = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAulas = new javax.swing.JTable();
        txtEdificioAulas = new javax.swing.JTextField();
        txtCapacidadAulas = new javax.swing.JTextField();
        txtIDAula = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblEscudo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAula = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonIngresarAulas.setBackground(new java.awt.Color(218, 127, 143));
        ButtonIngresarAulas.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonIngresarAulas.setText("INGRESAR");
        ButtonIngresarAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarAulasActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIngresarAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));

        ButtonEliminarAulas.setBackground(new java.awt.Color(218, 127, 143));
        ButtonEliminarAulas.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonEliminarAulas.setText("ELIMINAR");
        ButtonEliminarAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarAulasActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEliminarAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 470, 100, 30));

        ButtonModificarAulas.setBackground(new java.awt.Color(218, 127, 143));
        ButtonModificarAulas.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonModificarAulas.setText("MODIFICAR");
        ButtonModificarAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarAulasActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonModificarAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 110, 30));

        ButtonSalir.setBackground(new java.awt.Color(218, 127, 143));
        ButtonSalir.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonSalir.setText("REGRESAR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 470, 110, 30));

        tablaAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID AULA", "CAPACIDAD", "ID EDIFICIO"
            }
        ));
        jScrollPane2.setViewportView(tablaAulas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 170, 470, 240));

        txtEdificioAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdificioAulasActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdificioAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 140, 30));
        jPanel1.add(txtCapacidadAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, 30));
        jPanel1.add(txtIDAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, 30));

        jPanel2.setBackground(new java.awt.Color(225, 229, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/urcuqui (1).png"))); // NOI18N
        jPanel2.add(lblEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel5.setText("UNIDAD EDUCATIVA 'URCUQUI'");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1000, 70));

        lblAula.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        lblAula.setForeground(new java.awt.Color(63, 183, 188));
        lblAula.setText("AULAS");
        jPanel1.add(lblAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jPanel3.setBackground(new java.awt.Color(167, 187, 199));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID AULA");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 100, 30));

        jPanel4.setBackground(new java.awt.Color(167, 187, 199));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAPACIDAD");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 100, 30));

        jPanel5.setBackground(new java.awt.Color(167, 187, 199));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID EDIFICIO");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 100, 30));

        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel6.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdificioAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdificioAulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdificioAulasActionPerformed

    private void ButtonIngresarAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarAulasActionPerformed
 try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlRegistro = "insert into aula (aula_capacidad, edi_id) values (?,?)";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlRegistro);
            stmt.setString(1, txtCapacidadAulas.getText());
            stmt.setString(2, txtEdificioAulas.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "registro exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
        {
        }    }//GEN-LAST:event_ButtonIngresarAulasActionPerformed

    private void ButtonEliminarAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarAulasActionPerformed
try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlEliminacion = "delete from aula where aula_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlEliminacion);
            stmt.setString(1, txtIDAula.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "Eliminación exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonEliminarAulasActionPerformed

    private void ButtonModificarAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarAulasActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlUpdate = "update aula set aula_capacidad=?, edi_id=? where aula_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlUpdate);
            stmt.setString(1, txtCapacidadAulas.getText());
            stmt.setString(2, txtEdificioAulas.getText());
            stmt.setString(3, txtIDAula.getText());
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                // Mensaje de confirmación
                JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente");
            } else {
                // Mensaje de error
                JOptionPane.showMessageDialog(null, "La ID no existe");
            }
            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonModificarAulasActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        MenuAdmin nf3 = new MenuAdmin();
        nf3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel6MouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
         System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        jPanel6.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        jPanel6.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aulas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminarAulas;
    private javax.swing.JButton ButtonIngresarAulas;
    private javax.swing.JButton ButtonModificarAulas;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAula;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTable tablaAulas;
    private javax.swing.JTextField txtCapacidadAulas;
    private javax.swing.JTextField txtEdificioAulas;
    private javax.swing.JTextField txtIDAula;
    // End of variables declaration//GEN-END:variables
}