/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Bienes extends javax.swing.JFrame{
    
    int xMouse, yMouse;

    public void mostrar() {
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sql = "Select * from bienes";
            Statement st = null;
            DefaultTableModel model = new DefaultTableModel();
            //añadir el nombre de la columna
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Descripción");
            model.addColumn("Aula");
            TablaBienes.setModel(model);

            String[] datos = new String[4];
            try {
                st = (Statement) conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getString(4);
                    model.addRow(datos);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            // Cerrar la conexión
            st.close();
            conn.close();
        } catch (SQLException e) {

        }
    }

    public Bienes() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonIngresoBienes = new javax.swing.JButton();
        ButtonEliminarBienes = new javax.swing.JButton();
        ButtonModificarBienes = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBienes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDBienes = new javax.swing.JTextField();
        txtNombreBienes = new javax.swing.JTextField();
        txtDescripcionBienes = new javax.swing.JTextField();
        txtAula = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonIngresoBienes.setBackground(new java.awt.Color(218, 127, 143));
        ButtonIngresoBienes.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonIngresoBienes.setText("INGRESAR");
        ButtonIngresoBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoBienesActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIngresoBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 30));

        ButtonEliminarBienes.setBackground(new java.awt.Color(218, 127, 143));
        ButtonEliminarBienes.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonEliminarBienes.setText("ELIMINAR");
        ButtonEliminarBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarBienesActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEliminarBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 100, 30));

        ButtonModificarBienes.setBackground(new java.awt.Color(218, 127, 143));
        ButtonModificarBienes.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonModificarBienes.setText("MODIFICAR");
        ButtonModificarBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarBienesActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonModificarBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 110, 30));

        ButtonSalir.setBackground(new java.awt.Color(218, 127, 143));
        ButtonSalir.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonSalir.setText("REGRESAR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 100, 30));

        TablaBienes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "AULA"
            }
        ));
        jScrollPane1.setViewportView(TablaBienes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 490, 240));

        jPanel2.setBackground(new java.awt.Color(225, 229, 234));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/urcuqui (1).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel6.setText("UNIDAD EDUCATIVA 'URCUQUI'");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1010, 70));

        txtIDBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDBienesActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, 30));

        txtNombreBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBienesActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 30));

        txtDescripcionBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionBienesActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcionBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 150, 30));

        txtAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 150, 30));

        jPanel4.setBackground(new java.awt.Color(167, 187, 199));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AULA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, 30));

        jPanel5.setBackground(new java.awt.Color(167, 187, 199));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 30));

        jPanel6.setBackground(new java.awt.Color(167, 187, 199));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DESCRIPCION");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jPanel7.setBackground(new java.awt.Color(167, 187, 199));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ID BIENES");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 30));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 183, 188));
        jLabel4.setText("BIENES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresoBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoBienesActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlRegistro = "insert into bienes (bie_nombre, bie_descripcion, aula_id) values (?,?,?)";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlRegistro);
            stmt.setString(1, txtNombreBienes.getText());
            stmt.setString(2, txtDescripcionBienes.getText());
            stmt.setString(3, txtAula.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "registro exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonIngresoBienesActionPerformed

    private void ButtonEliminarBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarBienesActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlEliminacion = "delete from bienes where bie_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlEliminacion);
            stmt.setString(1, txtIDBienes.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "Eliminación exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonEliminarBienesActionPerformed

    private void ButtonModificarBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarBienesActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlUpdate = "update bienes set bie_nombre=?, bie_descripcion=?, aula_id=? where bie_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlUpdate);
            stmt.setString(1, txtNombreBienes.getText());
            stmt.setString(2, txtDescripcionBienes.getText());
            stmt.setString(3, txtAula.getText());
            stmt.setString(4, txtIDBienes.getText());
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                // Mensaje de confirmación
                JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente");
            } else {
                // Mensaje de error
                JOptionPane.showMessageDialog(null, "La ID no existe");
            }
            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonModificarBienesActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        MenuAdmin nf3 = new MenuAdmin();
        nf3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void txtAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAulaActionPerformed

    private void txtNombreBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBienesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBienesActionPerformed

    private void txtDescripcionBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionBienesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionBienesActionPerformed

    private void txtIDBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDBienesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDBienesActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
         jPanel3.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        jPanel3.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminarBienes;
    private javax.swing.JButton ButtonIngresoBienes;
    private javax.swing.JButton ButtonModificarBienes;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JTable TablaBienes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTextField txtAula;
    private javax.swing.JTextField txtDescripcionBienes;
    private javax.swing.JTextField txtIDBienes;
    private javax.swing.JTextField txtNombreBienes;
    // End of variables declaration//GEN-END:variables
}