/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Edificio extends javax.swing.JFrame {
    int xMouse, yMouse;

    public void mostrar() {
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sql = "Select * from edificio";
            Statement st = null;
            DefaultTableModel model = new DefaultTableModel();
            //añadir el nombre de la columna
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Cantidad de aulas");
            model.addColumn("Descripción");
            TablaEdificio.setModel(model);

            String[] datos = new String[4];
            try {
                st = (Statement) conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getString(4);
                    model.addRow(datos);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            // Cerrar la conexión
            st.close();
            conn.close();
        } catch (SQLException e) {

        }
    }

    public Edificio() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ingresar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        ButtonModificarEdificio = new javax.swing.JButton();
        ButtonSalirEdificio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEdificio = new javax.swing.JTable();
        txtdescripcion = new javax.swing.JTextField();
        txtCapacidadEdificio = new javax.swing.JTextField();
        txtNombreEdificio = new javax.swing.JTextField();
        txtIDedificio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setBackground(new java.awt.Color(218, 127, 143));
        Ingresar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        Ingresar.setText("INGRESAR");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));

        eliminar.setBackground(new java.awt.Color(218, 127, 143));
        eliminar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 100, 30));

        ButtonModificarEdificio.setBackground(new java.awt.Color(218, 127, 143));
        ButtonModificarEdificio.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonModificarEdificio.setText("MODIFICAR");
        ButtonModificarEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonModificarEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 110, 30));

        ButtonSalirEdificio.setBackground(new java.awt.Color(218, 127, 143));
        ButtonSalirEdificio.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        ButtonSalirEdificio.setText("REGRESAR");
        ButtonSalirEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalirEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 100, 30));

        TablaEdificio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID EDIFICIO", "NOMBRE", "CAPACIDAD", "DESCRIPCION"
            }
        ));
        jScrollPane1.setViewportView(TablaEdificio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 180, 470, 250));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 140, 30));

        txtCapacidadEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadEdificioActionPerformed(evt);
            }
        });
        jPanel1.add(txtCapacidadEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 140, 30));
        jPanel1.add(txtNombreEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 140, 30));
        jPanel1.add(txtIDedificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 140, 30));

        jPanel2.setBackground(new java.awt.Color(225, 229, 234));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/urcuqui (1).png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel7.setText("UNIDAD EDUCATIVA 'URCUQUI'");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 678, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 960, 70));

        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 183, 188));
        jLabel6.setText("EDIFICIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jPanel3.setBackground(new java.awt.Color(167, 187, 199));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID EDIFICIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 30));

        jPanel4.setBackground(new java.awt.Color(167, 187, 199));

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DESCRIPCION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 120, 30));

        jPanel5.setBackground(new java.awt.Color(167, 187, 199));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AULAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jPanel6.setBackground(new java.awt.Color(167, 187, 199));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 272, 120, 30));

        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel7.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapacidadEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadEdificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadEdificioActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlRegistro = "insert into edificio (edi_nombre, edi_CantidadAulas, edi_descripcion) values (?,?,?)";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlRegistro);
            stmt.setString(1, txtNombreEdificio.getText());
            stmt.setString(2, txtCapacidadEdificio.getText());
            stmt.setString(3, txtdescripcion.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "registro exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_IngresarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlEliminacion = "delete from edificio where edi_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlEliminacion);
            stmt.setString(1, txtIDedificio.getText());
            int rowsAffected = stmt.executeUpdate();

            //Mensaje de confirmacion de registro
            JOptionPane.showMessageDialog(null, "Eliminación exitoso");

            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
        {
        }    }//GEN-LAST:event_eliminarActionPerformed

    private void ButtonModificarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarEdificioActionPerformed
        try {
            // Conectar a la base de datos
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/reservadeaulas", "root", "");

            // Realiza el comando Mysql
            String sqlUpdate = "update edificio set edi_nombre=?, edi_CantidadAulas=?, edi_descripcion=? where edi_id=?";
            PreparedStatement stmt = (PreparedStatement) conn.prepareStatement(sqlUpdate);
            stmt.setString(1, txtNombreEdificio.getText());
            stmt.setString(2, txtCapacidadEdificio.getText());
            stmt.setString(3, txtdescripcion.getText());
            stmt.setString(4, txtIDedificio.getText());
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                // Mensaje de confirmación
                JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente");
            } else {
                // Mensaje de error
                JOptionPane.showMessageDialog(null, "La ID no existe");
            }
            // Cerrar la conexión
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        mostrar();
    }//GEN-LAST:event_ButtonModificarEdificioActionPerformed

    private void ButtonSalirEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirEdificioActionPerformed
        MenuAdmin nf3 = new MenuAdmin();
        nf3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSalirEdificioActionPerformed

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel7MouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        jPanel7.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
         jPanel7.setBackground(Color.white);
        lblExit.setForeground(Color.black);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edificio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonModificarEdificio;
    private javax.swing.JButton ButtonSalirEdificio;
    private javax.swing.JButton Ingresar;
    private javax.swing.JTable TablaEdificio;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTextField txtCapacidadEdificio;
    private javax.swing.JTextField txtIDedificio;
    private javax.swing.JTextField txtNombreEdificio;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}