/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class MenuAdmin extends javax.swing.JFrame {

    int xMouse, yMouse;
     
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonUsuario = new javax.swing.JButton();
        ButtonEdificio = new javax.swing.JButton();
        buttonBienes = new javax.swing.JButton();
        ButtonAulas = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        ButtonRegistros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblEscudomnAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblExit3 = new javax.swing.JLabel();
        lblUsuadm = new javax.swing.JLabel();
        lblBienesadm = new javax.swing.JLabel();
        lblRegadm = new javax.swing.JLabel();
        lblEdifiadm = new javax.swing.JLabel();
        lblAulasadm = new javax.swing.JLabel();
        lblSaliradm = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(920, 480));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonUsuario.setBackground(new java.awt.Color(218, 127, 143));
        ButtonUsuario.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        ButtonUsuario.setText("Usuario");
        ButtonUsuario.setBorder(null);
        ButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, -1));

        ButtonEdificio.setBackground(new java.awt.Color(218, 127, 143));
        ButtonEdificio.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        ButtonEdificio.setText("Edificio");
        ButtonEdificio.setBorder(null);
        ButtonEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdificioActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, -1));

        buttonBienes.setBackground(new java.awt.Color(218, 127, 143));
        buttonBienes.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        buttonBienes.setText("Bienes");
        buttonBienes.setBorder(null);
        buttonBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBienesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBienes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 100, -1));

        ButtonAulas.setBackground(new java.awt.Color(218, 127, 143));
        ButtonAulas.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        ButtonAulas.setText("Aulas");
        ButtonAulas.setBorder(null);
        ButtonAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAulasActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, -1));

        ButtonSalir.setBackground(new java.awt.Color(218, 127, 143));
        ButtonSalir.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        ButtonSalir.setText("Salir");
        ButtonSalir.setBorder(null);
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 100, -1));

        ButtonRegistros.setBackground(new java.awt.Color(218, 127, 143));
        ButtonRegistros.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        ButtonRegistros.setText("Registros");
        ButtonRegistros.setBorder(null);
        ButtonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 100, -1));

        jPanel1.setBackground(new java.awt.Color(225, 229, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEscudomnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/urcuqui (1).png"))); // NOI18N
        jPanel1.add(lblEscudomnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        jLabel1.setText("UNIDAD EDUCATIVA 'URCUQUI'");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 930, 70));

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        lblExit3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblExit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit3.setText("X");
        lblExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExit3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lblUsuadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/icons8-usuario-90.png"))); // NOI18N
        getContentPane().add(lblUsuadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lblBienesadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/bienes.png"))); // NOI18N
        getContentPane().add(lblBienesadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        lblRegadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/registros.png"))); // NOI18N
        getContentPane().add(lblRegadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        lblEdifiadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/edificio.png"))); // NOI18N
        getContentPane().add(lblEdifiadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lblAulasadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/aulas.png"))); // NOI18N
        getContentPane().add(lblAulasadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        lblSaliradm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/salir.png"))); // NOI18N
        getContentPane().add(lblSaliradm, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        jPanel3.setBackground(new java.awt.Color(250, 243, 243));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUsuarioActionPerformed
        Usuarios nf4 = new Usuarios();
        nf4.setVisible(true);
        this.dispose();    }//GEN-LAST:event_ButtonUsuarioActionPerformed

    private void ButtonEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdificioActionPerformed
        Edificio nf5 = new Edificio();
        nf5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonEdificioActionPerformed

    private void buttonBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBienesActionPerformed
        Bienes nf6 = new Bienes();
        nf6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBienesActionPerformed

    private void ButtonAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAulasActionPerformed
        Aulas nf7 = new Aulas();
        nf7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonAulasActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        Login nf1 = new Login();
        nf1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
       int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
        jPanel2.setBackground(Color.white);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lblExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExit3MouseClicked

    private void lblExit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit3MouseEntered
         jPanel2.setBackground(Color.red);
        lblExit3.setForeground(Color.white);
    }//GEN-LAST:event_lblExit3MouseEntered

    private void lblExit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit3MouseExited
         jPanel2.setBackground(Color.white);
        lblExit3.setForeground(Color.black);
    }//GEN-LAST:event_lblExit3MouseExited

    private void ButtonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrosActionPerformed
         Registros nf8 = new Registros();
        nf8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAulas;
    private javax.swing.JButton ButtonEdificio;
    private javax.swing.JButton ButtonRegistros;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JButton ButtonUsuario;
    private javax.swing.JButton buttonBienes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAulasadm;
    private javax.swing.JLabel lblBienesadm;
    private javax.swing.JLabel lblEdifiadm;
    private javax.swing.JLabel lblEscudomnAdmin;
    private javax.swing.JLabel lblExit3;
    private javax.swing.JLabel lblRegadm;
    private javax.swing.JLabel lblSaliradm;
    private javax.swing.JLabel lblUsuadm;
    // End of variables declaration//GEN-END:variables
}
